name: CI

on:
  push:
    branches:
      - main      
  pull_request:
    branches:
      - main

jobs:
  
  iOS:
    name: Build iOS
    runs-on: macos-14
    env:
      DEVELOPER_DIR: /Applications/Xcode_15.3.app
      PROJECT_NAME: /SnapCopy.xcodeproj
      SCHEME_NAME: SnapCopy
    strategy:
      matrix:
        destination: ["name=iPhone 15 Pro"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: iOS - ${{ matrix.destination }}
        run: |
          set -o pipefail
          xcodebuild build -project "${{ env.PROJECT_NAME }}" -scheme "${{ env.SCHEME_NAME }}" -destination "${{ matrix.destination }}" -configuration Debug ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES ONLY_ACTIVE_ARCH=YES

