name: CI

on:
  push:
    branches:
      - main      
  pull_request:
    branches:
      - main

jobs:
  
  iOS:
    name: Build iOS
    runs-on: macos-14
    env:
      DEVELOPER_DIR: /Applications/Xcode_15.3.app      
    strategy:
      matrix:
        destination: ["name=iPhone 15 Pro"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: iOS - ${{ matrix.destination }}
        run: fastlane build_app
