name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-14

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Xcode version
      run: sudo xcode-select -s /Applications/Xcode_15.3.app/Contents/Developer

    - name: Install xcpretty
      run: gem install xcpretty

    - name: Build project
      run: xcodebuild -project /Users/runner/work/SnapCopy/SnapCopy/SnapCopy/SnapCopy.xcodeproj -scheme SnapCopy -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15 Pro' clean build | xcpretty

    - name: Test project
      run: xcodebuild -project /Users/runner/work/SnapCopy/SnapCopy/SnapCopy/SnapCopy.xcodeproj -scheme PackagesTests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15 Pro' clean build test | xcpretty
