name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Xcode
      uses: actions/setup-xcode@v2
      with:
        version: '15.3'  

    - name: Install xcpretty
      run: gem install xcpretty

    - name: Build project
      run: xcodebuild -scheme YourSchemeName -destination "platform=iOS Simulator,name=iPhone 12" clean build | xcpretty
