name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-14

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Xcode version
      run: sudo xcode-select -s /Applications/Xcode_15.3.app/Contents/Developer

    - name: Install xcpretty
      run: gem install xcpretty

    - name: Debug Directory Contents
      run: ls -la /Users/runner/work/SnapCopy/SnapCopy

    - name: Build project
      run: xcodebuild -project /SnapCopy/SnapCopy.xcodeproj -scheme SnapCopy clean build | xcpretty
