name: CI

on:
  push:
    branches:
      - main      
  pull_request:
    branches:
      - main

jobs:
  
  iOS:
    name: Build iOS
    runs-on: macos-14
    steps:
      - name: Build 
        uses: actions/checkout@v2
        run: fastlane build_app
