name: CI

on:
  push:
    branches:
      - main      
  pull_request:
    branches:
      - main

jobs:
  
  iOS:
    name: Build iOS
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: iOS - ${{ matrix.destination }}
        run: fastlane build_app
